// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"eCommerce/customer/controllers"
	"eCommerce/customer/infrastructure"
	"eCommerce/customer/repositories"
	"eCommerce/customer/services"
)

// Injectors from wire.go:

func Init() func() {
	customerRespository := repositories.ProvideCustomerRepository()
	customerService := &services.CustomerService{
		Repository: customerRespository,
	}
	customerController := controllers.CustomerController{
		CustomerService: customerService,
	}
	handlers := infrastructure.Handlers{
		CustomerController: customerController,
	}
	v := infrastructure.ProvideServer(handlers)
	return v
}
