// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"eCommerce/order/controllers"
	"eCommerce/order/infrastructure"
	"eCommerce/order/repositories"
	"eCommerce/order/services"
)

// Injectors from wire.go:

func Init() func() {
	orderRespository := repositories.ProvideOrderRepository()
	orderService := &services.OrderService{
		Repository: orderRespository,
	}
	orderController := controllers.OrderController{
		OrderService: orderService,
	}
	handlers := infrastructure.Handlers{
		OrderController: orderController,
	}
	v := infrastructure.ProvideServer(handlers)
	return v
}
